import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import CartSidebar from "../components/CartSidebar";
import Navigation from "../components/Navigation";
import HydrationGuard from "../components/HydrationGuard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-50">
        <Navigation />
        <main className="flex-1 flex flex-col pt-16">
          <HydrationGuard>{typeof window !== 'undefined' ? children : null}</HydrationGuard>
        </main>
        <CartSidebar />
      </body>
    </html>
  );
}
